apiVersion: v1
kind: Service
metadata:
  name: eks-test
  labels:
    app: eks-test
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: nginx
  selector:
    app: eks-test
